# Generated by Django 5.1 on 2025-03-16 22:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('is_due', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_borrowed', models.DateField(default=datetime.date.today)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loanees.loanee')),
            ],
        ),
    ]
